# Generated by Django 3.1.6 on 2021-02-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('size', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('update_time', models.DateTimeField(verbose_name='update date')),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
